version: '3'
services:
    backend:
      build:
        context: ./
      networks:
        - main
      ports:
        - "4000:4000"
      environment:
        - DEFAULT_PASS=$DEFAULT_PASS
    database:
        image: 'mongo'
        container_name: 'mongo-db'
        volumes:
            - ./mongo-volume:/data/db
        networks:
          - main
networks:
  main:
